<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "information".
 *
 * @property integer $id
 * @property string $name_uz
 * @property string $name_ru
 * @property string $description_uz
 * @property string $description_ru
 * @property integer $photos
 * @property integer $the_world
 * @property string $image
 * @property integer $status
 * @property integer $is_deleted
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $created_by
 * @property integer $updated_by
 * @property string $aliasModel
 */
abstract class Information extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'information';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['description_uz', 'description_ru'], 'string'],
            [['photos', 'the_world', 'status', 'is_deleted'], 'integer'],
            [['name_uz', 'name_ru', 'image'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'name_uz' => Yii::t('models', 'Name Uz'),
            'name_ru' => Yii::t('models', 'Name Ru'),
            'description_uz' => Yii::t('models', 'Description Uz'),
            'description_ru' => Yii::t('models', 'Description Ru'),
            'photos' => Yii::t('models', 'Photos'),
            'the_world' => Yii::t('models', 'The World'),
            'image' => Yii::t('models', 'Image'),
            'status' => Yii::t('models', 'Status'),
            'is_deleted' => Yii::t('models', 'Is Deleted'),
            'created_at' => Yii::t('models', 'Created At'),
            'updated_at' => Yii::t('models', 'Updated At'),
            'created_by' => Yii::t('models', 'Created By'),
            'updated_by' => Yii::t('models', 'Updated By'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\Information the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\Information(get_called_class());
    }


}
