<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "user_address".
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $name
 * @property string $family
 * @property string $patronymic_name
 * @property string $series
 * @property string $series_num
 * @property string $pin_fl
 * @property string $birth_date
 * @property string $address
 * @property string $sera_num
 * @property integer $status
 * @property integer $is_deleted
 * @property integer $created_at
 * @property integer $updated_at
 *
 * @property \common\models\User $user
 * @property string $aliasModel
 */
abstract class UserAddress extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'user_address';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id'], 'integer'],
            [['name', 'family', 'patronymic_name', 'series', 'series_num', 'pin_fl', 'birth_date', 'address'], 'string', 'max' => 255],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\User::className(), 'targetAttribute' => ['user_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'name' => 'Name',
            'family' => 'Family',
            'patronymic_name' => 'Patronymic Name',
            'series' => 'Series',
            'series_num' => 'Series Num',
            'pin_fl' => 'Pin Fl',
            'birth_date' => 'Birth Date',
            'address' => 'Address',
            'status' => 'Status',
            'is_deleted' => 'Is Deleted',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',

        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\common\models\User::className(), ['id' => 'user_id']);
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\UserAddress the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\UserAddress(get_called_class());
    }


}
